# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        main_config:
            height: 600
            toolbar: 
                - ['Undo', 'Redo']
                - ['Bold', 'Italic', 'Underline', 'Strike']
                - ['Link', 'Unlink']
                - ['NumberedList', 'BulletedList']
                - ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
                - ['Image', 'MediaEmbed', 'Table']
                - ['Format']
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            extraPlugins: ['mediaembed','justify']